"""empty message

Revision ID: 299ca10fdcc5
Revises: d6729a56f925
Create Date: 2023-08-30 20:08:19.825587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299ca10fdcc5'
down_revision = 'd6729a56f925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(length=15), nullable=True))
    op.add_column('students', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'password')
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
