"""empty message

Revision ID: 5a98177f4b6d
Revises: 299ca10fdcc5
Create Date: 2023-08-30 20:12:08.465223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a98177f4b6d'
down_revision = '299ca10fdcc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'bio',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'bio',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
