"""empty message

Revision ID: 70c9feb04d92
Revises: e9bd83c9872d
Create Date: 2023-08-23 20:54:20.777727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70c9feb04d92'
down_revision = 'e9bd83c9872d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'image',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'image',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
