"""empty message

Revision ID: d6729a56f925
Revises: 
Create Date: 2023-08-26 17:27:38.974858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6729a56f925'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('surname', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=15), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('students_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['students_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    op.drop_table('students')
    # ### end Alembic commands ###
